// Router
export const ROUTER_ROUTING = "ROUTER_ROUTING";

// // USER
// export const USER_LOGIN_START = "USER_LOGIN_START";
// export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
// export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
// export const USER_LOGOUT_START = "USER_LOGOUT_START";
