// flow-typed signature: 3e8778b6055749a4cad831f9963e0c94
// flow-typed version: <<STUB>>/nedb-promise_v^2.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nedb-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nedb-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nedb-promise/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nedb-promise/index' {
  declare module.exports: $Exports<'nedb-promise'>;
}
declare module 'nedb-promise/index.js' {
  declare module.exports: $Exports<'nedb-promise'>;
}
declare module 'nedb-promise/test.js' {
  declare module.exports: $Exports<'nedb-promise/test'>;
}
